### ISSUE TITLE
koa2 support

### ISSUE THREAD

**Issue by jpravetz** [LucianoGanga/koa-restify-mongoose#4]
I've forked this package and am in the process of updating it for koa2. koa2 is not backward compatible, although there are compatibility wrappers. Most other repos seem to be using a new branch on existing koa1 repos for koa2, rather than a new repo. Your thoughts? I can submit the changes back when I'm done, or publish a new koa2-restify-mongoose repo.

**Comment by LucianoGanga** [comment]
Hi jpravetz! Sorry for the late reply, I didn't see the notification about your message. 

I assume you already done this work, so I don't think my opinion would be useful now. Anyway, I was thinking that maybe the best option for you was forking the original project (express-restify-mongoose), that added a few updates since I made this module. 

Besides of that, and about the question about the repos used for koa1 and koa2 versions, I think it would be more intuitive using a new repo called koa2-restify-mongoose. 

Let me know when you finish the module, I can add the link to the description of this repo. 

Cheers!
Luciano

**Comment by jpravetz** [comment]
Hi Luciano,

I ended up working off of a different fork of express-restify-mongoose. You
can see the discussion here
<https://github.com/florianholzapfel/express-restify-mongoose/issues/329>.

Jim
